name: Prepare the Ansible AWX Execution Environment build
description: prep the environment for building
inputs:
  image:
    description: 'Base Directory of image to build'
    required: true
    type: string
  github_token:
    description: 'Github token for logging into container registry'
    required: true
    type: string
runs:
  using: "composite"

  steps:
    - name: Checkout awx-ee
      uses: actions/checkout@v3
      with:
        repository: ansible/awx-ee
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ env.VERSION }}
        path: ansible-awx-ee-build

