---
name: "Local Build Action for ansible-awx"
description: "Perform pre-build steps"
runs:
  using: "composite"
  steps:
    - name: Checkout awx
      uses: actions/checkout@v3
      with:
        repository: ansible/awx
        ref: ${{ env.VERSION }}
        path: ansible-awx

    - name: Checkout awx-logos
      uses: actions/checkout@v2
      with:
        repository: ansible/awx-logos
        path: awx-logos

