---
name: Build ansible-awx docker images

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths: ansible-awx/**

  workflow_dispatch:

jobs:
  build_ansible_awx:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare
        id: prep
        with:
          image: ansible-awx
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build
        with:
          image: ansible-awx
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_args: |
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ env.VERSION }}
            HEADLESS=False

