---
name: Build ansible-awx docker images

on:
  push:
    branches: [ "main" ]
    paths: ansible-awx/**

  workflow_dispatch:

jobs:
  build_ansible_awx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare
        id: prep
        with:
          image: ansible-awx
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build
        with:
          image: ansible-awx
          github_token: ${{ secrets.GITHUB_TOKEN }}

