---
name: Build lab Git Server

on:
  push:
    branches: [ "main" ]
    paths: git_server/**

  workflow_dispatch:

jobs:
  build_git_server:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare
        id: prep
        with:
          image: git_server
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build
        with:
          image: git_server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.prep.output.tags }}
          labels: ${{ steps.prep.output.labels }}
