---
name: Build Lab Images
run-name: Build/Publish ${{ inputs.image }} by @${{ github.actor }}
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: Image to build
        options:
          - ansible-awx
          - ansible-awx-ee
          - awx
          - git_server
jobs:
  images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ env.build_images }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: "Determine image directories changed in the last commit"
        shell: bash
        run: |
          git diff --name-only HEAD~1 | while read p ; do
            echo $p | awk -F/ '{print $1}' ;
          done | { grep -v github || true; } | sort | uniq > /tmp/changed_images
          echo "build_images<<EOF" >> $GITHUB_ENV
          cat /tmp/changed_images | jq -R | jq -s -M -c >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        if: github.event.inputs.image == ''

      - name: "Determine images to build from input"
        shell: bash
        run: |
          echo "build_images<<EOF" >> $GITHUB_ENV
          echo "${{ inputs.image }}" | jq -R | jq --slurp -M -c >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        if: github.event.inputs.image != ''

      - shell: bash
        run: "echo Will build the following images: $build_images"

  build:
    runs-on: ubuntu-latest
    needs: images
    if: ${{ needs.images.outputs.images != '[]' }}
    strategy:
      fail-fast: true
      matrix:
        image: ${{fromJson(needs.images.outputs.images)}}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare
        id: prep
        with:
          image: ${{ matrix.image }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-Build actions
        uses: ./.github/actions/pre_build
        with:
          image: ${{ matrix.image }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./${{ env.BUILD_CONTEXT || matrix.image }}
          cache-from: "type=gha,scope=docker-buildx-${{ matrix.image }}-${{ env.VERSION }}"
          cache-to: "type=gha,scope=docker-buildx-${{ matrix.image }}-${{ env.VERSION }}"
          tags: ${{ env.TAGS }}
          labels: ${{ env.LABELS }}
          platforms: linux/arm64,linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
            ${{ env.BUILD_ARGS }}
      - uses: ./.github/actions/build
        with:
          image: ${{ matrix.image }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
