---
name: Build ansible-awx docker images

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths: ansible-awx/**

  workflow_dispatch:

jobs:
  build_ansible_awx:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare
        with:
          image: ansible-awx
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout awx
        uses: actions/checkout@v3
        with:
          repository: ansible/awx
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.VERSION }}
          path: ansible-awx-build

      - name: Checkout awx-logos
        uses: actions/checkout@v2
        with:
          repository: ansible/awx-logos
          token: ${{ secrets.GITHUB_TOKEN }}
          path: awx-logos

      - name: Build AWX
        working-directory: ansible-awx-build
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
        run: |
          ansible-playbook -v tools/ansible/build.yml \
          -e awx_image=$IMAGE_NAME \
          -e awx_version=$VERSION \
          -e ansible_python_interpreter=$(which python3) \
          -e push=no \
          -e awx_official=yes

      - name: Build and publish image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./${{ env.BUILD_CONTEXT || inputs.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ env.VERSION }}
            HEADLESS=False
