name: Manual Build

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Base Directory of image to build'
        required: true

jobs:
  manual_build:
    uses: ./.github/workflows/build.yml

